global:
  scrape_interval:     15s
  evaluation_interval: 15s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'prometheus-stack-monitor'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  # - "first.rules"
  # - "second.rules"

scrape_configs:

  - job_name: 'prometheus-server'

    scrape_interval: 10s
    scrape_timeout: 5s

    static_configs:
        #- targets: ['localhost:9090']
      - targets: ['127.0.0.1:9090']

        #   - job_name: 'machine-vm'
        # 
        #     scrape_interval: 10s
        #     scrape_timeout: 5s
        # 
        #     static_configs:
        #       - targets: ['cadvisor:8080']

  - job_name: 'prometheus-pushgateway'

    scrape_interval: 10s
    scrape_timeout: 5s

    static_configs:
        #- targets: ['localhost:9091']
        #- targets: ['127.0.0.1:9091']
      - targets: ['prometheus-pushgateway:9091']
  
  - job_name: 'rchain-node'

    scrape_interval: 10s
    scrape_timeout: 5s

    static_configs:
        #- targets: ['localhost:9091']
        #- targets: ['127.0.0.1:9095']
      - targets: ['rchain-node:9095']
